@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
UniquePersonList -right-> Person

Person *--> Name
Person *--> Age
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> StartDate
Person *--> "*" Tag
Person *--> "*" AvailableDay
Person *--> "*" RunTiming

Class RunTiming {
    distance: String
    minutes: int
    seconds: double
}
@enduml
